import { useEffect, useState } from 'react'
import type { FormEvent, ReactNode } from 'react'
import { NavLink, Navigate, Route, Routes, useNavigate } from 'react-router-dom'
import { api, login, session, type Admin } from './api'

const menu=[['/','Dashboard','▦'],['/usuarios','Usuários','♙'],['/partidas','Partidas','◉'],['/configuracao','Configuração do jogo','⚙'],['/gateway','Gateway Zypher','◇'],['/economia','Economia','◈'],['/ranking','Ranking','♛'],['/antifraude','Antifraude','⚠'],['/logs','Logs','≡']] as const

function Login({onLogin}:{onLogin:(a:Admin)=>void}) {
  const [error,setError]=useState(''),[loading,setLoading]=useState(false)
  const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setLoading(true);const f=new FormData(e.currentTarget);try{onLogin(await login(String(f.get('email')),String(f.get('password'))))}catch(x){setError(x instanceof Error?x.message:'Erro')}finally{setLoading(false)}}
  return <main className="login"><section><div className="brand">🦆 <b>Buraco Doido</b><span>Admin</span></div><h1>Bem-vindo de volta</h1><p>Acesse o painel operacional.</p><form onSubmit={submit}><label>E-mail<input name="email" type="email" required/></label><label>Senha<input name="password" type="password" minLength={8} required/></label>{error&&<div className="error">{error}</div>}<button disabled={loading}>{loading?'Entrando…':'Entrar no painel'}</button></form></section></main>
}
function Layout({admin,onLogout}:{admin:Admin;onLogout:()=>void}) {
  return <div className="layout"><aside><div className="brand">🦆 <b>Buraco Doido</b><span>Admin</span></div><nav>{menu.map(([to,label,icon])=><NavLink key={to} to={to} end={to==='/' }><i>{icon}</i>{label}</NavLink>)}</nav><div className="account"><span>{admin.name[0]}</span><div><b>{admin.name}</b><small>{admin.role}</small></div><button onClick={onLogout}>↪</button></div></aside><main className="content"><Routes><Route path="/" element={<Dashboard/>}/><Route path="/usuarios" element={<DataPage title="Usuários" endpoint="/users" kind="users"/>}/><Route path="/partidas" element={<DataPage title="Partidas" endpoint="/games" kind="games"/>}/><Route path="/configuracao" element={<ConfigPage/>}/><Route path="/gateway" element={<GatewayPage canEdit={admin.role==='SUPER_ADMIN'}/>}/><Route path="/economia" element={<DataPage title="Economia" endpoint="/coin-transactions" kind="economy"/>}/><Route path="/ranking" element={<DataPage title="Ranking" endpoint="/rankings" kind="ranking"/>}/><Route path="/antifraude" element={<DataPage title="Antifraude" endpoint="/fraud-alerts" kind="fraud"/>}/><Route path="/logs" element={admin.role==='SUPER_ADMIN'?<DataPage title="Logs de auditoria" endpoint="/audit-logs" kind="logs"/>:<Navigate to="/"/>}/></Routes></main></div>
}
function Dashboard(){
  const [data,setData]=useState<Record<string,number>|null>(null),[period,setPeriod]=useState('today')
  useEffect(()=>{api<Record<string,number>>(`/dashboard?period=${period}`).then(setData)},[period])
  const cards=[['Jogadores',data?.users,'♙'],['Ativos',data?.activeUsers,'●'],['Partidas',data?.games,'◉'],['Concluídas',data?.finished,'✓'],['Média',Math.round(data?.averageScore||0),'⌁'],['Recorde',data?.highestScore,'♛'],['Moedas',data?.coinsDistributed,'◈'],['Alertas',data?.fraudAlerts,'⚠']]
  return <><Header title="Visão geral" subtitle="Indicadores reais da operação."><select value={period} onChange={e=>setPeriod(e.target.value)}><option value="today">Hoje</option><option value="7d">Últimos 7 dias</option><option value="30d">Últimos 30 dias</option></select></Header><div className="cards">{cards.map(([l,v,i])=><article key={String(l)}><i>{i}</i><small>{l}</small><strong>{data?Number(v||0).toLocaleString('pt-BR'):'—'}</strong></article>)}</div><section className="panel"><h2>Saúde da operação</h2><div className="health"><span>Taxa de conclusão</span><b>{data?.completionRate||0}%</b><progress value={data?.completionRate||0} max="100"/></div></section></>
}
function Header({title,subtitle,children}:{title:string;subtitle:string;children?:ReactNode}){return <header><div><h1>{title}</h1><p>{subtitle}</p></div>{children}</header>}
type CharacterConfig={code:string;name:string;visual:string;points:number;frequency:number;timeBonus:number;isActive:boolean}
type Version={gameDuration:number;holeCount:number;minVisibleTime:number;maxVisibleTime:number;minimumStake:number;maximumStake:number;comboX2:number;comboX3:number;maximumScore:number;resetComboOnMiss:boolean;version:number;characters:CharacterConfig[]}
function ConfigPage(){
  const [config,setConfig]=useState<{id:string;name:string;versions:Version[]}|null>(null),[form,setForm]=useState<Version|null>(null),[message,setMessage]=useState('')
  useEffect(()=>{api<{items:{id:string;name:string;versions:Version[]}[]}>('/game-configs').then(({items})=>{const first=items[0];if(first){setConfig(first);setForm(structuredClone(first.versions[0]))}})},[])
  const number=(key:keyof Version,value:string)=>setForm(old=>old?{...old,[key]:Number(value)}:old)
  const character=(index:number,key:'points'|'frequency'|'timeBonus',value:string)=>setForm(old=>old?{...old,characters:old.characters.map((c,i)=>i===index?{...c,[key]:Number(value)}:c)}:old)
  const characterActive=(index:number,value:boolean)=>setForm(old=>old?{...old,characters:old.characters.map((c,i)=>i===index?{...c,isActive:value}:c)}:old)
  const save=async()=>{if(!config||!form)return;setMessage('Salvando…');try{await api(`/game-configs/${config.id}`,{method:'PATCH',body:JSON.stringify(form)});setMessage('Nova versão publicada com sucesso.')}catch(e){setMessage(e instanceof Error?e.message:'Erro')}}
  if(!form)return <div className="empty">Carregando configuração…</div>
  const groups=[
    {title:'Estrutura da rodada',description:'Controla o tempo, quantidade de buracos e dificuldade visual.',fields:[
      ['gameDuration','Duração da rodada','Tempo total de uma partida, em segundos.',10,300,1],['holeCount','Quantidade de buracos','Número de posições disponíveis no tabuleiro.',4,25,1],
      ['minVisibleTime','Visibilidade no fim','Tempo mínimo que um alvo permanece visível, em milissegundos.',200,3000,50],['maxVisibleTime','Visibilidade no início','Tempo máximo de exibição no começo da rodada.',200,5000,50],
      ['maximumScore','Pontuação máxima','Teto de pontos permitido por partida.',100,1000000,100],
    ]},
    {title:'Valores e limites',description:'Define a faixa de entrada exibida e aceita pela API.',fields:[
      ['minimumStake','Entrada mínima (R$)','Menor valor permitido para iniciar uma rodada.',1,100000,1],['maximumStake','Entrada máxima (R$)','Maior valor permitido para iniciar uma rodada.',1,100000,1],
    ]},
    {title:'Combos',description:'Define quando os multiplicadores de pontos entram em ação.',fields:[
      ['comboX2','Combo para 2×','Quantidade de acertos consecutivos para dobrar os pontos.',2,100,1],['comboX3','Combo para 3×','Quantidade de acertos consecutivos para triplicar os pontos.',3,200,1],
    ]},
  ] as {title:string;description:string;fields:[keyof Version,string,string,number,number,number][]}[]
  return <><Header title="Configuração do jogo" subtitle={`Editando ${config?.name} · versão ${form.version}`}/><div className="config-notice"><b>Como funciona o versionamento?</b><span>Cada publicação cria uma nova versão. Partidas já iniciadas continuam usando as regras anteriores.</span></div><section className="panel config-form">{groups.map(group=><div className="config-group" key={group.title}><div className="config-heading"><h2>{group.title}</h2><p>{group.description}</p></div><div className="field-grid">{group.fields.map(([key,label,help,min,max,step])=><label className="explained-field" key={key}><span>{label}</span><small>{help}</small><input type="number" min={min} max={max} step={step} value={Number(form[key])} onChange={e=>number(key,e.target.value)}/></label>)}</div></div>)}<div className="config-group"><div className="config-heading"><h2>Comportamento do combo</h2><p>Escolha o que acontece quando o jogador deixa um alvo escapar.</p></div><label className="switch-field"><input type="checkbox" checked={form.resetComboOnMiss} onChange={e=>setForm({...form,resetComboOnMiss:e.target.checked})}/><span><b>Zerar combo ao errar</b><small>Quando ativo, qualquer erro ou alvo perdido reinicia a sequência.</small></span></label></div><div className="config-group"><div className="config-heading"><h2>Personagens e valores</h2><p>Ative personagens e defina pontos, chance de aparição e bônus de tempo. A frequência dos ativos deve somar 100%.</p></div><div className="character-table">{form.characters.map((c,i)=><div key={c.code}><span className="character-name"><b>{c.visual} {c.name}</b><label className="mini-switch"><input type="checkbox" checked={c.isActive} onChange={e=>characterActive(i,e.target.checked)}/> Ativo</label></span><label>Pontos<small>Valor ao acertar</small><input type="number" value={c.points} onChange={e=>character(i,'points',e.target.value)}/></label><label>Frequência %<small>Chance de aparecer</small><input type="number" min="0" max="100" value={c.frequency} onChange={e=>character(i,'frequency',e.target.value)}/></label><label>Bônus (s)<small>Tempo acrescentado</small><input type="number" min="0" max="60" value={c.timeBonus} onChange={e=>character(i,'timeBonus',e.target.value)}/></label></div>)}</div></div><div className="config-actions"><button className="save-button" onClick={save}>Publicar nova versão</button>{message&&<span className="save-message">{message}</span>}</div></section></>
}

type Gateway={provider:string;enabled:boolean;baseUrl:string;clientId:string;hasClientSecret:boolean;updatedAt:string|null}
function GatewayPage({canEdit}:{canEdit:boolean}){
 const [gateway,setGateway]=useState<Gateway|null>(null),[secret,setSecret]=useState(''),[message,setMessage]=useState(''),[testing,setTesting]=useState(false)
 useEffect(()=>{api<{gateway:Gateway}>('/payment-gateway').then(data=>setGateway(data.gateway)).catch(error=>setMessage(error.message))},[])
 const save=async()=>{if(!gateway)return;setMessage('Salvando…');try{const data=await api<{gateway:Gateway}>('/payment-gateway',{method:'PUT',body:JSON.stringify({enabled:gateway.enabled,baseUrl:gateway.baseUrl,clientId:gateway.clientId,...(secret?{clientSecret:secret}:{})})});setGateway(data.gateway);setSecret('');setMessage('Configuração salva com segurança.')}catch(error){setMessage(error instanceof Error?error.message:'Falha ao salvar.')}}
 const test=async()=>{setTesting(true);setMessage('Testando conexão…');try{const data=await api<{message:string}>('/payment-gateway/test',{method:'POST'});setMessage(data.message)}catch(error){setMessage(error instanceof Error?error.message:'Falha no teste.')}finally{setTesting(false)}}
 if(!gateway)return <div className="empty">Carregando gateway…</div>
 return <><Header title="Gateway Zypher" subtitle="Credenciais usadas para cash-in PIX e cash-out."/><div className="gateway-intro"><span>◇</span><div><b>Zypher Pay</b><p>A API autentica cada requisição pelos headers X-Client-Id e X-Client-Secret. O Secret ID é criptografado e nunca volta para o navegador.</p></div><em className={gateway.enabled?'connected':'disabled'}>{gateway.enabled?'Habilitado':'Desabilitado'}</em></div><section className="panel gateway-form"><div className="config-heading"><h2>Credenciais da API</h2><p>Você encontra essas informações no painel Zypher em Dashboard → API.</p></div><label className="explained-field"><span>URL da API</span><small>Endereço base da Zypher. Em produção, use https://api.zypher.global.</small><input type="url" value={gateway.baseUrl} disabled={!canEdit} onChange={e=>setGateway({...gateway,baseUrl:e.target.value})}/></label><label className="explained-field"><span>Client ID</span><small>Identifica a chave utilizada pela sua aplicação.</small><input value={gateway.clientId} disabled={!canEdit} autoComplete="off" onChange={e=>setGateway({...gateway,clientId:e.target.value})}/></label><label className="explained-field"><span>Secret ID</span><small>{gateway.hasClientSecret?'Já existe um segredo salvo. Deixe vazio para mantê-lo ou digite outro para substituir.':'Informe o segredo da chave no primeiro cadastro.'}</small><input type="password" value={secret} disabled={!canEdit} autoComplete="new-password" placeholder={gateway.hasClientSecret?'••••••••••••••••':'Cole o Secret ID'} onChange={e=>setSecret(e.target.value)}/></label><label className="switch-field"><input type="checkbox" checked={gateway.enabled} disabled={!canEdit} onChange={e=>setGateway({...gateway,enabled:e.target.checked})}/><span><b>Habilitar Zypher</b><small>Ativa o gateway para novas operações. Salve e teste antes de usar em produção.</small></span></label><div className="gateway-security"><b>Proteção das credenciais</b><p>O Secret ID é armazenado com AES-256-GCM. Trocas de configuração ficam registradas nos logs de auditoria sem gravar o segredo.</p></div><div className="config-actions">{canEdit&&<button className="save-button" onClick={save}>Salvar credenciais</button>}<button className="test-button" disabled={testing||!gateway.hasClientSecret} onClick={test}>{testing?'Testando…':'Testar conexão'}</button>{message&&<span className="save-message">{message}</span>}</div></section></>
}
function DataPage({title,endpoint,kind}:{title:string;endpoint:string;kind:string}){
 const [items,setItems]=useState<Record<string,unknown>[]>([]),[error,setError]=useState(''),[search,setSearch]=useState('')
 useEffect(()=>{api<{items:Record<string,unknown>[]}>(endpoint).then(d=>setItems(d.items||[])).catch(e=>setError(e.message))},[endpoint])
 const shown=items.filter(x=>JSON.stringify(x).toLowerCase().includes(search.toLowerCase()))
 return <><Header title={title} subtitle={`${items.length} registros encontrados.`}/><div className="toolbar"><input placeholder="Buscar…" value={search} onChange={e=>setSearch(e.target.value)}/><button>Exportar</button></div>{error?<div className="error">{error}</div>:<section className="panel table-wrap"><table><thead><tr><th>Identificação</th><th>Detalhes</th><th>Status</th><th>Data</th></tr></thead><tbody>{shown.map((x,i)=><tr key={String(x.id||i)}><td><b>{String(x.name||x.userId||x.id||'Registro')}</b><small>{String(x.email||x.type||'')}</small></td><td>{kind==='games'?`${x.score||0} pts · ${x.hits||0} acertos`:kind==='ranking'?`${x.bestScore||0} pts`:String(x.action||x.reason||x.role||'—')}</td><td><span className={`badge ${String(x.status||x.riskLevel||'ACTIVE').toLowerCase()}`}>{String(x.status||x.riskLevel||'ATIVO')}</span></td><td>{x.createdAt?new Date(String(x.createdAt)).toLocaleDateString('pt-BR'):'—'}</td></tr>)}</tbody></table>{!shown.length&&<div className="empty">Nenhum registro para exibir.</div>}</section>}</>
}
export default function App(){
 const [admin,setAdmin]=useState<Admin|null>(null),[loading,setLoading]=useState(Boolean(session.get()));const nav=useNavigate()
 useEffect(()=>{if(session.get())api<{admin:Admin}>('/auth/me').then(d=>setAdmin(d.admin)).catch(session.clear).finally(()=>setLoading(false))},[])
 if(loading)return <div className="splash">🦆</div>;if(!admin)return <Login onLogin={setAdmin}/>
 return <Layout admin={admin} onLogout={()=>{api('/auth/logout',{method:'POST'}).catch(()=>{});session.clear();setAdmin(null);nav('/')}}/>
}
